### ISSUE TITLE
The Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [jipp/unifiedSensorLib#1]
In the file "unifiedSensorLib/lib/Sensors/Sensor.cpp", in the second readRegister8() function, there is a Wire.endTransmission() at the end of that function. That Wire.endTransmission() can be removed.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by jipp** [comment]
Thx 
Fixed

> Am 29.06.2018 um 17:09 schrieb Koepel <notifications@github.com>:
> 
> Wire.endTransmission
